name: C/C++ CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task1
    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make test
